### ISSUE TITLE
How did you find all those memory values, and which method youre using to maintain syncrhonization??

### ISSUE THREAD

**Issue by francot514** [Sleepy93/DriverMP#1]
Hey just found the source for this project, and im really interesting in understand how did you find all that info, and which method youre using to maintan server-client ?? just tcpclient socket needed??

**Comment by Sleepy93** [comment]
Hello

Finding memory values and addresses... for it need Cheat Engine and practise about using CT.
Try Cheat Engine with the tutorial and after it find any games and monitor with it, try to find values etc.
Need to find player position coordinates in RAM, and check addresses, pointers if there are.
Document everything well because it's easier to work on it.

About the code: 
The Client (Program.cs)
>BUFFER_SIZE = packet size
>NetSend() - Data sending
>NetRec() - Data recieving

Socket through TCPClient
Server (Program.cs)
>BUFFER_SIZE = packet size
>ConnectCheck() - Handling connections
>NetTrans(byte id) - Recieving data, sending to everyone else

Socket through TCPListener
I hope it'll be more clearly after it.

**Comment by francot514** [comment]
I understand what you say, about CT you mean CheatTables?? I have worked with it in Driver 2 for PSone, but im not able to find those advanced values like player position or pointers to player data, will be possible do something similar using this method and Psone emulator?

**Comment by Sleepy93** [comment]
First of all you need to go to a higher position on the map (mountain or topside of a building...) 
after it go down to the street and check decreased values,  go back to upper position and check increased values ... and more .. after a few scans you might find the player's position x,y,z and maybe with rotation values. 

if you have the X,Y,Z coords try to change the value of it, if it's not changed dynamically than you can use directly.
if it's changing dynamically then you need to find the pointer of player positions.

**Comment by francot514** [comment]
Ok, i have found some values in game for player position, but dont know how to find those specific values you labeled in CT as Player, CarSpawn, Traffic and how to make to advance options to be able to spawn another "Player"..

**Comment by Sleepy93** [comment]
The multiplayer client uses a custom folder called mp. The files in it has the spawning scripted. The client only moves these cars. Using this: First traffic address + offset * player ID.
You can find the traffic by searching for the density value (64 is the max value and 16 is the minimum). Use the Find out what writes to this address on the found value.

**Comment by francot514** [comment]
But all those files are copied from missions, you had reused those?? In case of driver 2 seems no clue about player spawn, all what i have achieved is to sync two players mode positions, but want to add the traffic if possible. Also why you removed those in latest?

**Comment by Sleepy93** [comment]
We used those files to add vehicles that will be moved later by other players. These vehicles are hidden from players until they are needed. Traffic was removed because it wasn't in sync and couldn't be. Cars that were spawned with the mission script don't take draw distance into account, so it's easier to sync players with that.

**Comment by francot514** [comment]
Whats next todo no more udpates planned?

**Comment by Sleepy93** [comment]
Unfortunately we don't have more time for doing it.
I planned some features tried to add but didn't work well so that's egy there aren't any new releases.
